### ISSUE TITLE
greenwich misplotted in the US (near chicago) for 'prince'?

### ISSUE THREAD

**Issue by jgravois** [jtpio/music-globe#1] opened 2015-12-30 18:21 UTC
very cool project!

i'm not positive exactly what's going on, but something looks odd when comparing the top few results in the chart and map when you search for and plot 'prince' shows on the globe.

![prince](http://www.okayplayer.com/wp-content/uploads/2014/02/prince-debuts-lp-for-new-girl-crew-feat.jpg)
looking at the map, chart and JSON, my best guess is that shows in greenwich are being plotted somewhere near Chicago, even though the lat/long in the payload are accurate

``` js
venue: {
  // ...
  city: "Greenwich",
  latitude: 51.4666667,
  longitude: 0
}
```

**Comment by jtpio** [comment] 2015-12-31 00:07
Good catch!
As you mentioned, the data retrieved from the Bandsintown API looks correct.
So it might be an issue with the WebGL Globe itself.

A quick search brought me to this: https://github.com/dataarts/webgl-globe/issues/29

I will have a closer look in a few days, but if you find something in the meantime, please let me know.

**Comment by jgravois** [comment] 2015-12-31 00:16
given that the rest of your data is plotting correctly, perhaps the falsy longitude of `0` is problematic downstream?

**Comment by jtpio** [comment] 2016-01-03 22:01
Yes good point. Should be reproducible.

**Comment by jtpio** [comment] 2016-01-07 21:07
I found the bug.
Cities were grouped by venue name, which corresponds to the city name alone. It turns out that there is a city called _London_ in Canada as well as the one in the UK. That's why the data from London (UK) was plotted next to Chicago.

Fixed by 3a70a1bca47b0a056f831e47860b59377771a43e.

**Closed as completed by jtpio** 2016-01-07 21:07 UTC
Labels: bug

**Comment by jgravois** [comment] 2016-01-07 21:08
nice work.  thanks for humoring me!

**Comment by jtpio** [comment] 2016-01-07 21:10
Thank you for spotting this tricky bug!
